// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMftKLWcobeq-eUTNNDUNkWtvAb8mDd2k',
    appId: '1:618508194508:web:7964506d6a81fa76aa6869',
    messagingSenderId: '618508194508',
    projectId: 'ynss-f8689',
    authDomain: 'ynss-f8689.firebaseapp.com',
    storageBucket: 'ynss-f8689.appspot.com',
    databaseURL: 'https://ynss-f8689-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1XRpKtfxOxgrZK9FC2jUoJFC_5leE0ZY',
    appId: '1:618508194508:android:ecfa0ba10669ab41aa6869',
    messagingSenderId: '618508194508',
    projectId: 'ynss-f8689',
    storageBucket: 'ynss-f8689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdM9tjTKTAqPYzFh0UvFMlXFckVhf8jI',
    appId: '1:618508194508:ios:162b02b9ccd27e93aa6869',
    messagingSenderId: '618508194508',
    projectId: 'ynss-f8689',
    storageBucket: 'ynss-f8689.appspot.com',
    iosBundleId: 'com.example.carewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMdM9tjTKTAqPYzFh0UvFMlXFckVhf8jI',
    appId: '1:618508194508:ios:7ed35034f8ab295faa6869',
    messagingSenderId: '618508194508',
    projectId: 'ynss-f8689',
    storageBucket: 'ynss-f8689.appspot.com',
    iosBundleId: 'com.example.carewise.RunnerTests',
  );
}
